[project]
name = "migrate"
version = "0.1.0"
requires-python = ">=3.12,<3.14"
dependencies = [
    "deviousutils[all]",
    "pandas",
    "tqdm",
    "ipywidgets",
    "jupyter",
    "olmo-eval-internal",
    "olmo-cookbook[beaker] @ git+https://github.com/allenai/olmo-cookbook",
]

[tool.uv.sources]
olmo-eval-internal = { path = "olmo-eval-internal", editable = true }
